### ISSUE TITLE
Multiple issues when mining is started again as soon as its finished

### ISSUE THREAD

**Issue by nxglabs** [nxglabs/Teamo_Dapp#5]
1. The entire mining rate amount is added to the balance and the timer doesnt start. For example in attached video mining was started at 0.96 balance which turned directly into 1.44 without any countup.
2. As can be seen in the attached video, the countdown timer automatically restarts after every 10 seconds.

https://user-images.githubusercontent.com/5486116/155896274-7aae659e-bf79-44ea-a8cf-5a13511b16e1.MOV

**Comment by prafullnavkar-nxg** [comment]
issues are resolved
